### ISSUE TITLE
Thanks for code refactoring

### ISSUE THREAD

**Issue by wangjia184** [JohnLua/SmallService#1]
Appreciated for code refactoring

1. Code is tidy,  structure is also clean
2. Test cases are added
3. A global lock is added for thread-safety
4. Code can be refined further

https://github.com/JohnLua/SmallService/blob/ac5f36029f5b2bb01e5c9753b144e3f3d4793a0b/SmallService/Service/MemoryRankService.cs#L22-L29

E.g. `SortedList.ContainsKey` and an `O(log(n))` operation, and `SortedList.Remove` is an `O(n)` operation is element is hit. But if the element is not found, the internal array does not need be arranged, then  `SortedList.Remove` is an `O(log(n))` operation. So it seems to me the  `SortedList.ContainsKey` determination is redundant

https://github.com/JohnLua/SmallService/blob/ac5f36029f5b2bb01e5c9753b144e3f3d4793a0b/SmallService/Service/MemoryCustomerScoreService.cs#L20-L24

Another example here, the same element is accessed multiple times while only one time access is required.

https://github.com/JohnLua/SmallService/blob/ac5f36029f5b2bb01e5c9753b144e3f3d4793a0b/SmallService/Service/MemoryLeaderBoardService.cs

The current approach implements vanilla code efficiency,  there might be other ways to be considered for better complexity and concurrency.

| Approach  | `Update` | `Rank` | `RankByCustomerId` |
| ------------- | ------------- | ------------- | ------------- |
| [SortedSet](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1?view=net-6.0) + Dictionary (current)  | `O(n)`  | `O(1)` | `O(log(n))` |
| [BinarySearch](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.binarysearch?view=net-6.0) + Dictionary  | `O(n)`  | `O(1)` | `O(log(n))` |
| SkipList+ Dictionary  | `O(log(n))`  | `O(log(n))` | `O(log(n))` |

**Comment by JohnLua** [comment]
Implementing a skiplist for this requirement is a difficult job, so I refactored it a little angin. When the SortedList add and remove an element, It finds an element by [binary search](https://source.dot.net/#System.Collections/System/Collections/Generic/SortedList.cs,183). This leaderboard updates the score of an existing customer needs to remove and add operations, and the time complexity is O(log(n)) + O(log(n)).

**Comment by wangjia184** [comment]
>  and the time complexity is O(log(n)) + O(log(n)).

That's not true.

Let's first consider the time complexity of Insertion Sort algorithm.  When we insert a new element in an **ordered** array, certainly we can leverage Binary Search to locate the position for the new element to be inserted, and that BS lookup is an `O(log(n))` procedure,  But why Insertion Sort best case is  `O(n)` rather than `O(log(n))`?

The reason is from the continuous memory storage. After the position is determined, we have to shift all the subsequent elements to make up a new blank placeholder for the new element, and that is an `O(n)` operation. 

This is the same for all data structures backed by continuous memory storage. It is impossible to achieve time complexity better than `O(n)` when using continuous memory storage.  That's the reason why AVL-tree/RB-tree/SkipList/etc were invented. Otherwise we don't need those complicated data structures, right?

SortedList is a data structures backed by arrays, which are continuous memory storage. So it is also impacted by this limiration. If you look at the documentation from Microsoft, this is also stated [there](https://learn.microsoft.com/en-US/dotnet/api/system.collections.sortedlist.add?view=net-7.0#remarks),
![image](https://github.com/JohnLua/SmallService/assets/2765840/14aaaab8-9344-42d1-97c9-d49ac6926218)
